env:
  browser: true
  es6: true
extends: 
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-process-env: 0
  no-script-url: 0
